import type { Product, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 1, name: 'Silk Sarees', slug: 'silk', image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80&fit=crop', display_order: 1, active: true },
  { id: 2, name: 'Kanchipuram', slug: 'kanchipuram', image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e5?w=800&q=80&fit=crop', display_order: 2, active: true },
  { id: 3, name: 'Cotton Sarees', slug: 'cotton', image: 'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=800&q=80&fit=crop', display_order: 3, active: true },
  { id: 4, name: 'Designer', slug: 'designer', image: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=800&q=80&fit=crop', display_order: 4, active: true },
  { id: 5, name: 'Bridal', slug: 'bridal', image: 'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=800&q=80&fit=crop', display_order: 5, active: true },
  { id: 6, name: 'Party Wear', slug: 'party-wear', image: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=800&q=80&fit=crop', display_order: 6, active: true },
];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Ruby Zari Kanchipuram Silk',
    slug: 'ruby-zari-kanchipuram-silk',
    category_id: 2,
    category: 'Kanchipuram',
    category_slug: 'kanchipuram',
    price: 18999,
    sale_price: 14999,
    description: 'A timeless Kanchipuram silk saree woven with traditional zari craftsmanship and a contemporary colour story. Handcrafted by master weavers from Kanchipuram, this piece embodies centuries of artistry.',
    fabric: 'Pure Kanchipuram Silk',
    colors: [{ name: 'Ruby', hex: '#9B2335' }, { name: 'Wine', hex: '#722F37' }, { name: 'Gold', hex: '#A88955' }],
    stock: 3,
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1583391733956-6c78276477e5?w=1200&q=85&fit=crop',
    ],
    featured: true,
    new_arrival: true,
    active: true,
  },
  {
    id: 2,
    name: 'Ivory Temple Kanjivaram',
    slug: 'ivory-temple-kanjivaram',
    category_id: 2,
    category: 'Kanchipuram',
    category_slug: 'kanchipuram',
    price: 22999,
    description: 'An ivory Kanjivaram with temple-border motifs in antique gold zari. Bridal-worthy and eternally elegant.',
    fabric: 'Pure Kanchipuram Silk',
    colors: [{ name: 'Ivory', hex: '#F7F2EA' }, { name: 'Gold', hex: '#A88955' }],
    stock: 5,
    images: [
      'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=1200&q=85&fit=crop',
    ],
    featured: true,
    new_arrival: false,
    active: true,
  },
  {
    id: 3,
    name: 'Midnight Banarasi Silk',
    slug: 'midnight-banarasi-silk',
    category_id: 1,
    category: 'Silk Sarees',
    category_slug: 'silk',
    price: 12999,
    description: 'Deep navy Banarasi with silver brocade work. For the woman who makes silence look loud.',
    fabric: 'Pure Banarasi Silk',
    colors: [{ name: 'Navy', hex: '#1B2A4A' }, { name: 'Silver', hex: '#C0C0C0' }],
    stock: 8,
    images: [
      'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=1200&q=85&fit=crop',
    ],
    featured: true,
    new_arrival: true,
    active: true,
  },
  {
    id: 4,
    name: 'Blush Organza Designer',
    slug: 'blush-organza-designer',
    category_id: 4,
    category: 'Designer',
    category_slug: 'designer',
    price: 8999,
    sale_price: 6999,
    description: 'Sheer blush organza with hand-embroidered floral accents. Contemporary, light, unforgettable.',
    fabric: 'Pure Organza',
    colors: [{ name: 'Blush', hex: '#D8B8B0' }, { name: 'Ivory', hex: '#F7F2EA' }],
    stock: 12,
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1583391733956-6c78276477e5?w=1200&q=85&fit=crop',
    ],
    featured: false,
    new_arrival: true,
    active: true,
  },
  {
    id: 5,
    name: 'Bridal Crimson Patola',
    slug: 'bridal-crimson-patola',
    category_id: 5,
    category: 'Bridal',
    category_slug: 'bridal',
    price: 34999,
    description: 'Double-ikat Patola in bridal crimson. A rare weave that takes months to complete. For the bride who deserves nothing less than extraordinary.',
    fabric: 'Pure Silk Patola',
    colors: [{ name: 'Crimson', hex: '#DC143C' }, { name: 'Gold', hex: '#A88955' }, { name: 'Ivory', hex: '#F7F2EA' }],
    stock: 2,
    images: [
      'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1583391733956-6c78276477e5?w=1200&q=85&fit=crop',
    ],
    featured: true,
    new_arrival: false,
    active: true,
  },
  {
    id: 6,
    name: 'Emerald Chanderi Cotton',
    slug: 'emerald-chanderi-cotton',
    category_id: 3,
    category: 'Cotton Sarees',
    category_slug: 'cotton',
    price: 4999,
    description: 'Lightweight emerald Chanderi cotton with gold buti. Perfect for everything from morning meetings to evening cocktails.',
    fabric: 'Chanderi Cotton Silk',
    colors: [{ name: 'Emerald', hex: '#50C878' }, { name: 'Gold', hex: '#A88955' }],
    stock: 20,
    images: [
      'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&q=85&fit=crop',
    ],
    featured: false,
    new_arrival: true,
    active: true,
  },
  {
    id: 7,
    name: 'Gold Tissue Party Silk',
    slug: 'gold-tissue-party-silk',
    category_id: 6,
    category: 'Party Wear',
    category_slug: 'party-wear',
    price: 9999,
    description: 'Tissue silk that catches every light in the room. Because some entrances deserve a standing ovation.',
    fabric: 'Tissue Silk',
    colors: [{ name: 'Gold', hex: '#A88955' }, { name: 'Champagne', hex: '#F7E7CE' }],
    stock: 7,
    images: [
      'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1583391733956-6c78276477e5?w=1200&q=85&fit=crop',
    ],
    featured: true,
    new_arrival: true,
    active: true,
  },
  {
    id: 8,
    name: 'Sage Linen Handloom',
    slug: 'sage-linen-handloom',
    category_id: 3,
    category: 'Cotton Sarees',
    category_slug: 'cotton',
    price: 3499,
    description: 'Breathable sage linen handloom. The art of looking effortlessly expensive without trying too hard.',
    fabric: 'Handloom Linen',
    colors: [{ name: 'Sage', hex: '#B2AC88' }, { name: 'Natural', hex: '#F5E6C8' }],
    stock: 15,
    images: [
      'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=1200&q=85&fit=crop',
    ],
    featured: false,
    new_arrival: false,
    active: true,
  },
  {
    id: 9,
    name: 'Burgundy Benarasi Brocade',
    slug: 'burgundy-benarasi-brocade',
    category_id: 1,
    category: 'Silk Sarees',
    category_slug: 'silk',
    price: 15999,
    description: 'Rich burgundy Banarasi with antique gold brocade. Old craft. New energy. Timeless attitude.',
    fabric: 'Pure Banarasi Silk',
    colors: [{ name: 'Burgundy', hex: '#641F2B' }, { name: 'Gold', hex: '#A88955' }],
    stock: 4,
    images: [
      'https://images.unsplash.com/photo-1583391733956-6c78276477e5?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&q=85&fit=crop',
    ],
    featured: true,
    new_arrival: false,
    active: true,
  },
  {
    id: 10,
    name: 'Dusty Rose Georgette',
    slug: 'dusty-rose-georgette',
    category_id: 4,
    category: 'Designer',
    category_slug: 'designer',
    price: 7499,
    description: 'Flowy georgette in dusty rose with subtle sequin embroidery. For the woman who is soft and strong in equal measure.',
    fabric: 'Premium Georgette',
    colors: [{ name: 'Dusty Rose', hex: '#DCAE96' }, { name: 'Nude', hex: '#E8CABA' }],
    stock: 9,
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=1200&q=85&fit=crop',
    ],
    featured: false,
    new_arrival: true,
    active: true,
  },
  {
    id: 11,
    name: 'Cobalt Blue Pochampally',
    slug: 'cobalt-blue-pochampally',
    category_id: 1,
    category: 'Silk Sarees',
    category_slug: 'silk',
    price: 11999,
    description: 'Vibrant cobalt Pochampally ikat with geometric patterns. Bold, beautiful, unmistakably Indian.',
    fabric: 'Ikat Silk',
    colors: [{ name: 'Cobalt', hex: '#0047AB' }, { name: 'White', hex: '#FFFFFF' }],
    stock: 6,
    images: [
      'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=1200&q=85&fit=crop',
    ],
    featured: false,
    new_arrival: false,
    active: true,
  },
  {
    id: 12,
    name: 'Champagne Chiffon Embroidered',
    slug: 'champagne-chiffon-embroidered',
    category_id: 6,
    category: 'Party Wear',
    category_slug: 'party-wear',
    price: 6999,
    sale_price: 5499,
    description: 'Delicate champagne chiffon with cut-dana embroidery on the border. The quiet choice that makes the loudest impression.',
    fabric: 'French Chiffon',
    colors: [{ name: 'Champagne', hex: '#F7E7CE' }, { name: 'Gold', hex: '#A88955' }],
    stock: 11,
    images: [
      'https://images.unsplash.com/photo-1583391733956-6c78276477e5?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&q=85&fit=crop',
    ],
    featured: false,
    new_arrival: true,
    active: true,
  },
  {
    id: 13,
    name: 'Marigold Kanchi Pure Silk',
    slug: 'marigold-kanchi-pure-silk',
    category_id: 2,
    category: 'Kanchipuram',
    category_slug: 'kanchipuram',
    price: 19999,
    description: 'Marigold Kanchipuram with peacock motifs in contrasting border. Sunshine woven into silk.',
    fabric: 'Pure Kanchipuram Silk',
    colors: [{ name: 'Marigold', hex: '#FCA329' }, { name: 'Green', hex: '#355E3B' }, { name: 'Gold', hex: '#A88955' }],
    stock: 3,
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1583391733956-6c78276477e5?w=1200&q=85&fit=crop',
    ],
    featured: false,
    new_arrival: true,
    active: true,
  },
  {
    id: 14,
    name: 'Indigo Block Print Cotton',
    slug: 'indigo-block-print-cotton',
    category_id: 3,
    category: 'Cotton Sarees',
    category_slug: 'cotton',
    price: 2999,
    description: 'Hand block-printed indigo cotton from Bagru. The kind of saree that feels like coming home.',
    fabric: 'Hand Block Print Cotton',
    colors: [{ name: 'Indigo', hex: '#4B0082' }, { name: 'White', hex: '#FFFFFF' }],
    stock: 25,
    images: [
      'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=1200&q=85&fit=crop',
    ],
    featured: false,
    new_arrival: false,
    active: true,
  },
  {
    id: 15,
    name: 'Bridal Red Kanchi Silk',
    slug: 'bridal-red-kanchi-silk',
    category_id: 5,
    category: 'Bridal',
    category_slug: 'bridal',
    price: 42999,
    description: 'The quintessential bridal Kanchipuram in vermilion red with heavy zari. For the most important day of her life.',
    fabric: 'Pure Kanchipuram Silk with Heavy Zari',
    colors: [{ name: 'Vermilion', hex: '#E34234' }, { name: 'Gold', hex: '#A88955' }],
    stock: 1,
    images: [
      'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1583391733956-6c78276477e5?w=1200&q=85&fit=crop',
    ],
    featured: true,
    new_arrival: false,
    active: true,
  },
  {
    id: 16,
    name: 'Teal Uppada Silk',
    slug: 'teal-uppada-silk',
    category_id: 1,
    category: 'Silk Sarees',
    category_slug: 'silk',
    price: 13499,
    description: 'Lightweight Uppada silk in deep teal with intricate jaal pattern. As comfortable as it is beautiful.',
    fabric: 'Pure Uppada Silk',
    colors: [{ name: 'Teal', hex: '#008080' }, { name: 'Gold', hex: '#A88955' }],
    stock: 5,
    images: [
      'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&q=85&fit=crop',
    ],
    featured: false,
    new_arrival: false,
    active: true,
  },
  {
    id: 17,
    name: 'Lavender Mysore Silk',
    slug: 'lavender-mysore-silk',
    category_id: 1,
    category: 'Silk Sarees',
    category_slug: 'silk',
    price: 8499,
    description: 'Smooth-as-butter Mysore silk in soft lavender with minimal silver border. Quietly luxurious.',
    fabric: 'Pure Mysore Silk',
    colors: [{ name: 'Lavender', hex: '#E6E6FA' }, { name: 'Silver', hex: '#C0C0C0' }],
    stock: 10,
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1583391733956-6c78276477e5?w=1200&q=85&fit=crop',
    ],
    featured: false,
    new_arrival: true,
    active: true,
  },
  {
    id: 18,
    name: 'Bridal Gold Tissue Kanchi',
    slug: 'bridal-gold-tissue-kanchi',
    category_id: 5,
    category: 'Bridal',
    category_slug: 'bridal',
    price: 38999,
    description: 'Gold tissue Kanchipuram with contrast ruby border. The kind of saree that makes a mother cry happy tears.',
    fabric: 'Tissue Kanchipuram Silk',
    colors: [{ name: 'Gold', hex: '#A88955' }, { name: 'Ruby', hex: '#9B111E' }],
    stock: 2,
    images: [
      'https://images.unsplash.com/photo-1583391733956-6c78276477e5?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=1200&q=85&fit=crop',
    ],
    featured: false,
    new_arrival: false,
    active: true,
  },
  {
    id: 19,
    name: 'Black Sequin Party Georgette',
    slug: 'black-sequin-party-georgette',
    category_id: 6,
    category: 'Party Wear',
    category_slug: 'party-wear',
    price: 7999,
    description: 'All-over black sequin georgette. A little drama never hurt anyone.',
    fabric: 'Sequin Georgette',
    colors: [{ name: 'Black', hex: '#0D0D0D' }, { name: 'Silver', hex: '#C0C0C0' }],
    stock: 6,
    images: [
      'https://images.unsplash.com/photo-1583391733956-6c78276477e5?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=1200&q=85&fit=crop',
    ],
    featured: false,
    new_arrival: true,
    active: true,
  },
  {
    id: 20,
    name: 'Forest Green Tussar Silk',
    slug: 'forest-green-tussar-silk',
    category_id: 1,
    category: 'Silk Sarees',
    category_slug: 'silk',
    price: 9999,
    description: 'Rich forest green Tussar with kalamkari border. Where heritage meets the forest.',
    fabric: 'Pure Tussar Silk',
    colors: [{ name: 'Forest', hex: '#228B22' }, { name: 'Rust', hex: '#B7410E' }],
    stock: 7,
    images: [
      'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=1200&q=85&fit=crop',
      'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=1200&q=85&fit=crop',
    ],
    featured: false,
    new_arrival: false,
    active: true,
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(slug: string): Product[] {
  return PRODUCTS.filter((p) => p.category_slug === slug && p.active);
}

export function getFeaturedProducts(): Product[] {
  return PRODUCTS.filter((p) => p.featured && p.active);
}

export function getNewArrivals(): Product[] {
  return PRODUCTS.filter((p) => p.new_arrival && p.active);
}

export function formatPrice(amount: number): string {
  return `₹${amount.toLocaleString('en-IN')}`;
}
